export const MAP_CONSTANTS = {
  INITIAL_ZOOM: 0.5,
  INITIAL_POSITION: {
    x: -1200,
    y: 0,
  },
  MIN_ZOOM: 0.25,
  MAX_ZOOM: 2,
  ANIMATION_DURATION: 500,
  WHEEL_ZOOM_SENSITIVITY: 0.05,
  BUTTON_ZOOM_STEP: 0.25,
} as const;
