import type { DepartmentTreeNode } from "../types/organization";

export const MOCK_DEPARTMENT_TREE: DepartmentTreeNode = {
  hierarchyId: 1,
  level: 1,
  title: "UDV GROUP",
  color: "#000000",
  children: [
    {
      hierarchyId: 2,
      level: 2,
      title: "UDV Digital Transformation",
      color: "#FF5733",
      children: [
        {
          hierarchyId: 5,
          level: 3,
          title: "ТриниДата",
          color: "#F39C12",
          children: [
            {
              hierarchyId: 12,
              level: 4,
              title: "Основное подразделение",
              color: "#7F8C8D",
              children: [],
            },
          ],
        },
        {
          hierarchyId: 6,
          level: 3,
          title: "ВНЕ ОЧЕРЕДИ",
          color: "#F39C12",
          children: [
            {
              hierarchyId: 13,
              level: 4,
              title: "Основное подразделение",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 14,
              level: 4,
              title: "Отдел продуктовой разработки",
              color: "#7F8C8D",
              children: [],
            },
          ],
        },
        {
          hierarchyId: 7,
          level: 3,
          title: "ФТ-СОФТ",
          color: "#F39C12",
          children: [
            {
              hierarchyId: 15,
              level: 4,
              title: "Администрация",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 16,
              level: 4,
              title: "Отдел продуктовой разработки 1",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 17,
              level: 4,
              title: "Отдел продуктовой разработки 2",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 18,
              level: 4,
              title: "Отдел заказной разработки",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 19,
              level: 4,
              title: "Основное подразделение",
              color: "#7F8C8D",
              children: [
                {
                  hierarchyId: 44,
                  level: 5,
                  title: "Направление Аналитики и документации",
                  color: "#95A5A6",
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      hierarchyId: 3,
      level: 2,
      title: "UDV Security",
      color: "#3498DB",
      children: [
        {
          hierarchyId: 8,
          level: 3,
          title: "КИТ",
          color: "#8E44AD",
          children: [
            {
              hierarchyId: 20,
              level: 4,
              title: "Администрация",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 21,
              level: 4,
              title: "Департамент консалтинга",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 22,
              level: 4,
              title: "Отдел сопровождения информационных систем",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 23,
              level: 4,
              title: "Департамент по работе с иностранными заказчиками",
              color: "#7F8C8D",
              children: [],
            },
          ],
        },
        {
          hierarchyId: 9,
          level: 3,
          title: "КИТ.Р",
          color: "#8E44AD",
          children: [
            {
              hierarchyId: 24,
              level: 4,
              title: "Администрация",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 25,
              level: 4,
              title: "Департамент разработки",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 26,
              level: 4,
              title: "Департамент кибербезопасности",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 27,
              level: 4,
              title: "Департамент маркетинга",
              color: "#7F8C8D",
              children: [],
            },
          ],
        },
        {
          hierarchyId: 10,
          level: 3,
          title: "Сайберлимфа",
          color: "#8E44AD",
          children: [
            {
              hierarchyId: 28,
              level: 4,
              title: "Отдел разработки",
              color: "#7F8C8D",
              children: [
                {
                  hierarchyId: 45,
                  level: 5,
                  title: "Группа серверной разработки",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 46,
                  level: 5,
                  title: "Группа веб разработки",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 47,
                  level: 5,
                  title: "Группа аналитики",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 48,
                  level: 5,
                  title: "Группа администрирования проектов",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 49,
                  level: 5,
                  title: "Группа продуктового дизайна",
                  color: "#7F8C8D",
                  children: [],
                },
              ],
            },
            {
              hierarchyId: 29,
              level: 4,
              title: "Коммерческий департамент",
              color: "#7F8C8D",
              children: [
                {
                  hierarchyId: 50,
                  level: 5,
                  title: "Отдел маркетинга",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 51,
                  level: 5,
                  title: "Отдел технической поддержки продаж",
                  color: "#7F8C8D",
                  children: [],
                },
              ],
            },
            {
              hierarchyId: 30,
              level: 4,
              title: "Лаборатория кибербезопасности",
              color: "#7F8C8D",
              children: [
                {
                  hierarchyId: 52,
                  level: 5,
                  title: "Производственное направление",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 53,
                  level: 5,
                  title: "Аналитическое направление",
                  color: "#7F8C8D",
                  children: [],
                },
                {
                  hierarchyId: 54,
                  level: 5,
                  title: "Отдел документирования и локализации",
                  color: "#7F8C8D",
                  children: [],
                },
              ],
            },
            {
              hierarchyId: 31,
              level: 4,
              title: "Администрация",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 32,
              level: 4,
              title: "Отдел персонала",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 33,
              level: 4,
              title: "Отдел технического сопровождения",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 34,
              level: 4,
              title: "Отдел интеграции и автоматизации",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 35,
              level: 4,
              title: "Отдел продуктового менеджмента",
              color: "#7F8C8D",
              children: [],
            },
          ],
        },
      ],
    },
    {
      hierarchyId: 4,
      level: 2,
      title: "UDV Services",
      color: "#2ECC71",
      children: [
        {
          hierarchyId: 11,
          level: 3,
          title: "Витропс",
          color: "#16A085",
          children: [
            {
              hierarchyId: 36,
              level: 4,
              title: "Администрация",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 37,
              level: 4,
              title: "Планово-экономический отдел",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 38,
              level: 4,
              title: "Отдел поддержки 1С",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 39,
              level: 4,
              title: "Отдел кадрового делопроизводства",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 40,
              level: 4,
              title: "Юридический отдел",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 41,
              level: 4,
              title: "Служба внутреннего сервиса",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 42,
              level: 4,
              title: "Отдел делопроизводства",
              color: "#7F8C8D",
              children: [],
            },
            {
              hierarchyId: 43,
              level: 4,
              title: "Бухгалтерия",
              color: "#7F8C8D",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
