import type { User } from "../types";

export const MOCK_USERS: Record<string, User> = {
    employee: {
        id: "1",
        firstName: "Иван",
        lastName: "Иванов",
        middleName: "Иванович",
        position: "Frontend Developer",
        department: {
            id: "1",
            name: "IT Department",
            color: "#3B82F6",
        },
        avatar: "",
        phone: "+79991234567",
        email: "user@udv.group",
        city: "Москва",
        interests: "Программирование, спорт",
        birthDate: "1990-01-01",
        hireDate: "2020-01-01",
        messengerLink: "https://t.me/ivanov",
    },
    hr: {
        id: "2",
        firstName: "Мария",
        lastName: "Петрова",
        middleName: "Сергеевна",
        position: "HR Manager",
        department: {
            id: "2",
            name: "HR Department",
            color: "#10B981",
        },
        avatar: "",
        phone: "+79997654321",
        email: "hr@udv.group",
        city: "Москва",
        interests: "HR, психология",
        birthDate: "1985-05-15",
        hireDate: "2019-03-10",
        messengerLink: "https://t.me/petrova_hr",
    },
    admin: {
        id: "3",
        firstName: "Алексей",
        lastName: "Сидоров",
        middleName: "Владимирович",
        position: "System Administrator",
        department: {
            id: "3",
            name: "IT Department",
            color: "#3B82F6",
        },
        avatar: "",
        phone: "+79995557777",
        email: "admin@udv.group",
        city: "Москва",
        interests: "Администрирование, сети",
        birthDate: "1988-08-20",
        hireDate: "2018-06-15",
        messengerLink: "https://t.me/sidorov_admin",
    },
};
